[package]
name = "bindgen"
version = "0.16.0"
description = "A binding generator for Rust"
authors = ["Jyun-Yan You <jyyou.tw@gmail.com>"]
license = "BSD-3-Clause"
homepage = "https://github.com/crabtw/rust-bindgen"
repository = "https://github.com/crabtw/rust-bindgen"
readme = "README.md"
keywords = [ "bindings", "ffi", "code-generation" ]
build = "build.rs"

[dependencies]
aster = { version = "0.21.1", features = ["with-syntex"] }
quasi = { version = "0.15", features = ["with-syntex"] }
clippy = { version = "*", optional = true }
syntex_syntax = "0.38"
log = "0.3.*"
env_logger = "*"
libc = "0.2.*"
clang-sys = "0.8.0"

[build-dependencies]
quasi_codegen = "0.15"

[features]
static = []
llvm_stable = []

[lib]
name = "bindgen"
path = "src/lib.rs"

[[bin]]
name = "bindgen"
doc = false

[[test]]
name = "tests"
